FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt ./requirements.txt
COPY server_chat_handler.py ./server_chat_handler.py

RUN pip install -r requirements.txt

CMD ["python3", "-u", "server_chat_handler.py"]