version: '3.8'
services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadserver
    ports:
      - "7000:7000"
    environment:
      - HOST=loadsv
      - PORT=7000
    depends_on:
      - server0
      - server1
      - server2
      - server3
      - server4
    networks:
      - drawnet

  server0:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - IN_PORT=8000
      - OUT_PORT=9000
    networks:
      - drawnet

  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - IN_PORT=8001
      - OUT_PORT=9001
    networks:
      - drawnet

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - IN_PORT=8002
      - OUT_PORT=9002
    networks:
      - drawnet

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - IN_PORT=8003
      - OUT_PORT=9003
    networks:
      - drawnet

  server4:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - IN_PORT=8004
      - OUT_PORT=9004
    networks:
      - drawnet

networks:
  drawnet:
